def replace_abbreviations():
    changed={
    "AA": "AS ABOVE",
    "AAF": "AS A MATTER OF FACT",
    "AAK": "ALIVE AND KICKING",
    "AAMOF": "AS A MATTER OF FACT",
    "AAMOI": "AS A MATTER OF INTEREST",
    "AAP": "ALWAYS A PLEASURE",
    "AAR": "AT ANY RATE",
    "AAS": "ALIVE AND SMILING",
    "AAYF": "AS ALWAYS, YOUR FRIEND",
    "ABD": "ALREADY BEEN DONE",
    "ABT": "ABOUT",
    "ABT2": "ABOUT TO",
    "ABU": "ALL BUGGED UP",
    "AC": "ACCEPTABLE CONTENT",
    "ACC": "ANYONE CAN COME",
    "ACD": "ALT / CONTROL / DELETE",
    "ACDNT": "ACCIDENT",
    "ACK": "ACKNOWLEDGE",
    "ACPT": "ACCEPT ",
    "ACQSTN": "ACQUISITION",
    "ADAD": "ANOTHER DAY, ANOTHER DOLLAR",
    "ADBB": "ALL DONE, BYE-BYE",
    "ADD": "ADDRESS",
    "ADIH": "ANOTHER DAY IN HELL",
    "ADIP": "ANOTHER DAY IN PARADISE",
    "ADMIN": "ADMINISTRATOR",
    "ADN": "ANY DAY NOW",
    "AE": "AREA EFFECT", 
    "AEAP": "AS EARLY AS POSSIBLE",
    "AF": "APRIL FOOLS",
    "AFC": "AWAY FROM COMPUTER",
    "AFAIAA": "AS FAR AS I AM AWARE",
    "AFAIC": "AS FAR AS I AM CONCERNED",
    "AFAIK": "AS FAR AS I KNOW",
    "AFAIUI": "AS FAR AS I UNDERSTAND IT",
    "AFAP": "AS FAR AS POSSIBLE",
    "AFFA": "ANGELS FOREVER, FOREVER ANGELS",
    "AFJ": "APRIL FOOL'S JOKE",
    "AFZ": "ACRONYM FREE ZONE",
    "AFPOE": "A FRESH PAIR OF EYES",
    "AH": "AT HOME",
    "AIAMU": "AND I AM A MONEY'S UNCLE",
    "AIR": "AS I REMEMBER",
    "AISB": "AS IT SHOULD BE",
    "AISB": "AS I SAID BEFORE",
    "AISI": "AS I SEE IT",
    "AITR": "ADULT IN THE ROOM",
    "AKA": "ALSO KNOWN AS",
    "ALOL": "ACTUALLY LAUGHING OUT LOUD",
    "AMA": "ASK ME ANYTHING",
    "AMAP": "AS MUCH AS POSSIBLE",
    "AMBW": "ALL MY BEST WISHES",
    "AML": "ALL MY LOVE",
    "AMOF": "AS A MATTER OF FACT",
    "AOE": "AREA OF EFFECT",
    "APP": "APPLICATION",
    "AQAP": "AS QUICK AS POSSIBLE",
    "ARC": "ARCHIVE",
    "ASIG": "AND SO IT GOES",
    "ASAP": "AS SOON AS POSSIBLE",
    "ASL": "AGE/SEX/LOCATION",
    "ASLA": "AGE/SEX/LOCATION/AVAILABILITY",
    "ATB": "ALL THE BEST",
    "ATEOTD": "AT THE END OF THE DAY",
    "AWOL": "AWAY WITHOUT LEAVING",
    "AYDY": "ARE YOU DONE YET",
    "AYBABTU": "ALL YOUR BASE ARE BELONG TO US", 
    "AYEC": "AT YOUR EARLIEST CONVENIENCE",
    "AYOR": "AT YOUR OWN RISK",
    "AYSOS": "ARE YOU STUPID OR SOMETHING",
    "AYS": "ARE YOU SERIOUS",
    "AYT": "ARE YOU THERE",
    "AYTMTB": "AND YOU'RE TELLING ME THIS BECAUSE",
    "AYW": "AS YOU WISH",
    "B&": "Banned",
    "B2B": "Business-to-business",
    "B2C": "Business-to-consumer",
    "B2W": "Back to work",
    "B8": "Bait",
    "B/F": "Boyfriend",
    "B/G": "Background",
    "B4": "Before",
    "B4N": "Bye for now",
    "BAE": "Before anyone else",
    "BAFO": "Best and final offer",
    "BAK": "Back at keyboard",
    "BAM": "Below average mentality",
    "BAO": "Be aware of",
    "BAS": "Big ass smile",
    "BASOR": "Breathing a sigh of relief",
    "BAU": "Business as usual",
    "BAY": "Back at you",
    "BB": "Be back",
    "BBC": "Big bad challenge",
    "BBIAB": "Be back in a bit",
    "BBIAF": "Be back in a few",
    "BBIAM": "Be back in a minute",
    "BBIAS": "Be back in a sec",
    "BBL": "Be back later",
    "BBQ": "Barbeque",
    "BBS": "Be back soon",
    "BBT": "Be back tomorrow",
    "B/C": "Because",
    "BCNU": "Be seeing you",
    "BCO": "Big crush on",
    "BCOY": "Big crush on you",
    "BD": "Big deal",
    "BDAY": "Birthday",
    "BF": "Boyfriend",
    "BFAW": "Best friend at work",
    "BFF": "Best friends forever",
    "BFFL": "Best friends for life",
    "BFFLNMW": "Best friends for life, no matter what",
    "BFD": "Big freaking deal",
    "BFFN": "Best friend for now",
    "BFN": "Bye for now",
    "BHL8": "Be home late",
    "BIB": "Boss is back",
    "BIBO": "Beer in, beer out",
    "BIH": "Burn in hell",
    "BIL": "Brother in law",
    "BION": "Believe it or not",
    "BIOYA": "Blow it out your ass",
    "BIOYN": "Blow it out your nose",
    "BIS": "Best in slot", 
    "BL": "Belly laugh",
    "BLNT": "Better luck next time",
    "BME": "Based on my experience",
    "BM&Y": "Between me and you",
    "BOL": "Best of luck",
    "BOOMS": "Bored out of my skull",
    "BOT": "Be on that",
    "BPLM": "Big person little mind",
    "BRB": "Be right back",
    "BR": "Best regards",
    "BRNC": "Be right back, nature calls",
    "BRH": "Be right here",
    "BRT": "Be right there",
    "BTA": "But then again",
    "BTDT": "Been there, done that",
    "BTW": "By the way",
    "BWL": "Bursting with laughter", 
    "BYTM": "Better you than me",
    "CAD": "Control + Alt + Delete",
    "CAM": "Camera",
    "CB": "Coffee break",
    "CD9": "Code 9",
    "CFS": "Care for secret",
    "CFY": "Calling for you",
    "CHK": "Check",
    "CICO": "Coffee in, coffee out",
    "CID": "Consider it done",
    "CLAB": "Crying like a baby",
    "CLK": "Click",
    "CM": "Call me",
    "CMAP": "Cover my ass partner",
    "CMB": "Call me back",
    "CMIIW": "Correct me if I'm wrong",
    "CMON": "Come on",
    "CNP": "Continued next post",
    "COB": "Close of business",
    "CP": "Chat post",
    "CR8": "Create",
    "CRB": "Come right back",
    "CRBT": "Crying really big tears", 
    "CRIT": "critical hit",
    "CRZ":  "Crazy",
    "CRS":  "Can't remember stuff",
    "CSL": "Can't stop laughing",
    "CSS": "Counter-Strike Source", 
    "CT": "Can't talk",
    "CTC": "Care to chat",
    "CTN": "Can't talk now",
    "CTO": "Check this out",
    "CU": "See you",
    "CUA": "See you around",
    "CUL": "See you later",
    "CUMID": "See you in my dreams",
    "CWOT": "Complete waste of time",
    "CWYL": "Chat with you later",
    "CX": "Correction",
    "D46": "Down for sex", "DA": "The",
    "DAE": "Does anyone else",
    "DAFUQ": "the Freak",
    "DAM": "Don't annoy me",
    "DBAU": "Doing business as usual",
    "DBEYR": "Don't believe everything you read",
    "DC": "Disconnect",
    "DDG": "Drop dead gorgeous",
    "DF": "Don't even go there",
    "DGA": "Don't go anywhere",
    "DGAF": "Don't give a fuck",
    "DGT": "Don't go there",
    "DGTG": "Don't go there, girlfriend",
    "DGYF": "Dang, girl you fine",
    "DIKU": "Do I know you",
    "DILLIGAF": "Do I look like I give a freak",
    "DIS": "Did I say",
    "DITYID": "Did I tell you I'm distressed",
    "DIY": "Do it yourself",
    "DKDC": "Don't know, don't care",
    "D/L": "Download",
    "DLTBBB": "Don't let the bed bugs bite",
    "DM": "Doesn't matter",
    "DMNO": "Dude Man No Offense",
    "DMY": "Don't mess yourself",
    "DNC": "Do not compute",
    "DNT": "Don't",
    "d00d": "Dude",
    "DPS": "Damage per second",
    "DQMOT": "Don't quote me on this",
    "DTR": "Define the relationship",
    "DTRT": "Do the right thing",
    "DTS": "Don't think so",
    "DUPE": "Duplicate",
    "DUR": "Do you remember",
    "DV8": "Deviate",
    "DXNRY": "Dictionary",
    "DYNWUTB": "Do you know what you are talking about",
    "DYFI": "Did you find it",
    "DYFM": "Dude, you fascinate me",
    "DYJHIW": "Don't you just hate it when",
    "DYOR": "Do your own research",
    "E1": "Everyone",
    "E123": "Easy as one, two, three",
    "EF4T": "Effort",
    "EG": "Evil grin",
    "ELI5": "Explain like I'm 5",
    "EM": "E-mail",
    "EMBAR": "Embarassing",
    "EMFBI": "Excuse me for butting in",
    "EMFBI": "Excuse me for jumping in",
    "ENUF": "Enough",
    "EOD": "End of discussion",
    "EOL": "End of lecture",
    "EOT": "End of transmission",
    "ETA": "Estimated time of arrival",
    "EVO": "Evolution",
    "EZ": "Easy",
    "EZY": "Easy",
    "F2F": "Face to face",
    "F2P": "Free to play",
    "F4F": "Follow for follow",
    "FAB": "Fabulous",
    "FAF": "Funny as fuck",
    "FAM": "Family",
    "FAQ": "Frequently asked questions",
    "FB": "Facebook",
    "FBB": "Facebook buddy",
    "FBC": "Facebook chat",
    "FBM": "Fine by me",
    "FBO": "Facebook official",
    "FBOW": "For better or worse",
    "FC": "Fingers crossed",
    "FC'INGO": "For crying out loud",
    "FF": "Follow Friday",
    "FFA": "Free for all",
    "FFS": "For fuck sakes",
    "FICCL": "Frankly I couldn't care a less",
    "FIF": "fuck I'm funny",
    "FIIK": "fuck if I know",
    "FIIOOH": "Forget it, I'm out of here",
    "FIL": "Father in law",
    "FIMH": "Forever in my heart",
    "FISH": "First in, still here",
    "FITB": "Fill in the blank",
    "FML": "fuck My Life",
    "FOMC": "Falling off my chair",
    "FOMO": "Fear of missing out",
    "FRT": "For real though",
    "FTBOMH": "From the bottom of my heart",
    "FTFY": "Fixed that for you",
    "FU": "fuck you",
    "FUBAR": "Fouled up beyond all recognition",
    "FW": "Forward",
    "FWB": "Friend with benefits",
    "FWIW": "For what it's worth",
    "FWM": "Fine with me",
    "FWP": "First world problems",
    "FYI": "For your information",
    "G+": "Google+",
    "G/F": "Girlfriend",
    "G2CU": "Good to see you",
    "G2G": "Got to go",
    "G2GICYAL8ER": "Got to go I'll see you later",
    "G2R": "Got to run",
    "G2TU": "Got to tell you",
    "G4C": "Going for coffee",
    "G9": "Genius",
    "GAL": "Get a life",
    "GB": "Goodbye",
    "GBTW": "Get back to work",
    "GBU": "God bless you",
    "GD": "Good",
    "GFN": "Gone for now",
    "GG": "Gotta Go",
    "GGE1": "Good game, everyone",
    "GGU2": "Good game, you too",
    "GIAR": "Give it a rest",
    "GIGO": "Garbage in, garbage out",
    "GL": "Good luck",
    "GL2U": "Good luck to you",
    "GLE1": "Good luck everyone",
    "GMBA": "Giggling my butt off",
    "GMTA": "Great minds think alike",
    "GN": "Good night",
    "GNA": "Good night all",
    "GNE1": "Good night everyone",
    "GNIGHT": "Good night",
    "GNITE": "Good night",
    "GNSD": "Good night, sweet dreams",
    "GOAT": "Greatest of all Time",
    "GR8": "Great",
    "GRL": "Girl",
    "GTFO": "Get the fuck out",
    "GTFOH": "Get the fuck outta here",
    "GUD": "Good",
    "GWHTLC": "Glad we had this little chat",
    "H8": "Hate",
    "H8TTU": "Hate to be you",
    "HAK": "Hug and kiss",
    "HALP": "Help",
    "HAU": "How about you",
    "H&K": "Hugs & kisses",
    "H2CUS": "Hope to see you soon",
    "HAGN": "Have a good night",
    "HAWT": "hot",
    "HB": "Hurry back",
    "HBD": "Happy birthday",
    "H-BDAY": "Happy Birthday",
    "HBU": "How about you",
    "HIFW": "How I felt when",
    "HLA": "hello",
    "HMU": "Hit me up",
    "HP": "Hit points", 
    "HRU": "How are you",
    "HTH": "Hope this helps",
    "HW": "Homework",
    "HYFR": "Hell yeah, fucking right",
    "I2": "I too",
    "IA8": "I already ate",
    "IAC": "In any case",
    "IB": "I'm back",
    "IC": "I see",
    "ICAM": "I couldn't agree more",
    "ICBW": "It could be worse",
    "ICFILWU": "I could fall in love with you",
    "ICYMI": "In case you missed it",
    "IDBI": "I don't believe it",
    "IDC": "I don't care",
    "IDK": "I don't know",
    "IDTS": "I don't think so",
    "IDUNNO": "I don't know",
    "IFYP": "I feel your pain",
    "IG": "Instagram",
    "IG2R": "I got to run",
    "IIRC": "If I remember correctly",
    "IK": "I know",
    "ILBL8": "I'll be late",
    "ILU": "I love you",
    "ILYSM": "I love you so much",
    "IM": "Instant message",
    "IMAO": "In my arrogant opinion",
    "IMHO": "In my humble opinion",
    "IMU": "I miss you",
    "INC": "incoming",
    "INV": "Invite",
    "ITYK": "I thought you knew",
    "IUSS": "If you say so",
    "IWALU": "I will always love you",
    "IWAWO": "I want a way out",
    "IYQ": "I like you",
    "IYSS": "If you say so",
    "j00": "You",
    "j00r": "Your",
    "JAC": "Just a second",
    "JAM": "Just a minute",
    "JAS": "Just a second",
    "JC": "Just checking",
    "JFF": "Just for fun",
    "JIC": "Just in case",
    "JJ ": "Just joking",
    "JJA": "Just joking around",
    "JK": "Just kidding",
    "JLMK": "Just let me know",
    "JMO": "Just my opinion",
    "JTLYK": "Just to let you know",
    "JW": "Just wondering",
    "K": "Okay",
    "KK": "Knock, knock",
    "K8T": "Katie",
    "KB": "Keyboard",
    "KEWL": "Cool",
    "KEYA": "I will key you later",
    "KEYME": "Key me when you get in",
    "KFY": "Kiss for you",
    "KIA": "Know it all",
    "KIR": "Keep it real",
    "KISS": "Keep it simple, stupid",
    "KMA": "Kiss my ass",
    "KMS": "Killing myself",
    "KOS": "Kid over shoulder",
    "KOTD": "Kicks of the day",
    "KNIM": "Know what I mean",
    "KNOW": "knowledge",
    "KS": "Kill then steal",
    "KUTGW": "Keep up the good work",
    "KYS": "Kill yourself",
    "L2G": "Like to go",
    "L2G": "Love to go",
    "L2K": "Like to come",
    "L2P": "Learn to play",
    "l33t": "elite",
    "L4L": "Like for like", 
    "L8R": "Later",
    "L8RG8R": "Later, gator",
    "LAB": "Life is a bitch",
    "LBAY": "Laughing back at you",
    "LD": "Long distance",
    "LDO": "Like, duh obviously",
    "LEMENO": "Let me know",
    "LFD": "Left for day",
    "LGH": "Lets get high",
    "LH6": "Lets have sex",
    "LHSX": "Lets have sex",
    "LHM": "Lord help me",
    "LHO": "Laughing head off",
    "LI": "LinkedIn",
    "LIC": "Like I care",
    "LLGB": "Love, later, God bless",
    "LLS": "Laughing like silly",
    "LMAO": "Laughing my ass off",
    "LMBO": "Laughing my butt off",
    "LMFAO": "Laughing my freaking ass off",
    "LMK": "Let me know",
    "LMMFAO": "Laughing my mother freaking ass off",
    "LNT": "lost in translation",
    "LOA": "List of acronyms",
    "LOL": "Lots of love",
    "LOLWTF": "Laughing out loud What the freak",
    "LOTI": "Laughing on the inside",
    "LOTR": "Lord of The Rings",
    "LQTM": "Laughing quietly to myself",
    "LSV": "Language, sex and violence",
    "LTNS": "Long time no see",
    "LULT": "Love you long time",
    "LULZ": "joke",
    "LVM": "Left voice mail",
    "LY": "Love ya",
    "LYSM": "Love you so much",
    "M$": "Microsoft",
    "M8": "Mate",
    "MC": "Merry Christmas",
    "MDIAC": "My Dad is a cop",
    "MEH": "just okay",
    "MEHH": "sigh",
    "MEZ": "mesmerize",
    "MFI": "Mad for it",
    "MFW": "My face when",
    "MGB": "May God bless",
    "MGMT": "Management",
    "MHOTY": "My hat is off to you",
    "MIRL": "Me in real life",
    "MKAY": "Mmm, okay",
    "MMK": "Meaning okay",
    "MNC": "Mother nature calls",
    "MNSG": "message",
    "MOD": "Moderator",
    "MOO": "My own opinion",
    "MOSS": "Member of same sex",
    "MRW": "My reaction when",
    "MSG": "Message",
    "MTFBWU": "May the force be with you",
    "MU": "Miss you",
    "MUSM": "Miss you so much",
    "MWAH": "kiss",
    "MYO": "Mind your own",
    "MYOB": "Mind your own business",
    "n00b": "Newbie",
    "N1": "Nice one",
    "N2M": "Nothing too much",
    "NADT": "Not a darn thing",
    "NANA": "Not now, no need",
    "NBD": "No big deal",
    "NBFAB": "No bad for a beginner",
    "NE": "Any",
    "NE1": "Anyone",
    "NFM": "None for me",
    "NGL": "Not gonna lie",
    "NFS": "Need for Speed",
    "NFW": "No fucking way",
    "NIGI": "Now I get it",
    "NMJC": "Nothing much, just chilling",
    "NMU": "Not much, you",
    "NO1": "No one",
    "NOWL": "knowledge",
    "NOYB": "None of your business",
    "NP": "No problem",
    "NRN": "No reply necessary",
    "NTHING": "Nothing",
    "NVM": "Never mind",
    "NVR": "Never",
    "NWO": "No way out",
    "O4U": "Only for you",
    "OA": "Online auctions",
    "OATUS": "On a totally unrelated subject",
    "OB": "Oh baby",
    "OBV": "Obviously",
    "OFC": "Of course",
    "OGIM": "Oh God, it's Monday",
    "OHHEMMGEE": "Oh My God",
    "OIB": "Oh, I'm back",
    "OIC": "Oh, I see",
    "OJ": "Only joking",
    "OM": "Oh, my",
    "OMAA": "Oh, my aching ass",
    "OMDB": "Over my dead body",
    "OMFG": "Oh my fucking God",
    "OMG": "Oh my God",
    "OMGYG2BK": "Oh my God, you got to be kidding",
    "OMGYS": "Oh my gosh you suck",
    "OMW": "On my way",
    "ONL": "Online",
    "OO": "Over and out",
    "OOH": "Out of here",
    "ORLY": "Oh really",
    "OS": "Operating system",
    "OTB": "Off to bed",
    "OTFL": "On the floor laughing",
    "OTL": "Out to lunch",
    "OTOH": "On the other hand",
    "OTP": "One time password",
    "OVA": "Over",
    "OYO": "On your own",
    "P2P": "Peer to peer",
    "P911": "Parents coming into room alert",
    "PAP": "Post a picture",
    "PAT": "patrol",
    "PAW": "Parents are watching",
    "PBOOK": "Phonebook",
    "PC": "Player character",
    "PCM": "Please call me",
    "PDA": "Personal display of affection",
    "PDS": "Please don't shoot",
    "PEEPS": "People",
    "PFT": "Pretty fucking tight",
    "PIC": "Picture",
    "PIP": "Peeing in pants",
    "PITA": "Pain in the ass",
    "PKMN": "Pokemon",
    "PL8": "Plate",
    "PLD": "Played",
    "PLMK": "Please let me know",
    "PLS": "Please",
    "PLZ": "Please",
    "PLZTLME": "Please tell me",
    "PM": "Private Message",
    "PMFI": "Pardon me for interrupting",
    "PMFJI": "Pardon me for jumping in",
    "PMSL": "Pee myself laughing",
    "POV": "Point of view",
    "PPL": "People",
    "PRESH": "Precious",
    "PROBS": "Probably",
    "PROLLY": "Probably",
    "PROGGY": "computer program",
    "PORN": "pornography",
    "PRT": "Party",
    "PSA": "Public Service Announcement",
    "PSP": "Playstation Portable",
    "PST": "Please send tell",
    "PTFO": "Pass the fuck out",
    "PTO": "Personal time off",
    "PUG": "Pick up group",
    "PVE": "Player vs enemy",
    "PVP": "Player versus player",
    "PU": "That stinks",
    "PZ": "Peace",
    "PZA": "Pizza",
    "Q": "Queue",
    "Q4U": "question for you",
    "QC": "Quality control",
    "QFE": "Question for everyone",
    "QIK": "Quick",
    "QL": "Quit laughing",
    "QOTD": "Quote of the day",
    "QQ": "Quick question",
    "QSL": "Reply",
    "QSO": "Conversation",
    "QT": "Cutie",
    "QTPI": "Cutie pie",
    "R": "are",
    "R8": "Rate",
    "RBAY": "Right back at you",
    "RFN": "Right fucking now",
    "RGR": "Roger",
    "RIP": "Rest in peace",
    "RL": "Real life",
    "RLY": "Really",
    "RME": "Rolling my eyes",
    "RMLB": "Read my lips baby",
    "ROFL": "Rolling on floor laughing",
    "ROFLCOPTER": "Rolling on floor laughing and spinning around",
    "ROFLMAO": "Rolling on the floor, laughing my ass off",
    "ROTFL": "Rolling on the floor laughing",
    "RTFM": "Read the fucking manual",
    "RTFQ": "Read the fucking question",
    "RTHX": "Thanks for the Retweet",
    "RTNTN": "Retention",
    "RTRCTV": "Retroactive",
    "RTRMT": "Retirement",
    "RTSM": "Read the stupid manual",
    "RU": "Are you",
    "RUT": "Are you there",
    "RUOK": "Are you okay",
    "RX": "Regards",
    "RYO": "Roll your own",
    "RYS": "Read your screen", 
    "RYS1": "Are you single",
    "S2S": "Sorry to say",
    "S4L": "Spam for life",
    "SAL": "Such a laugh",
    "SAT": "Sorry about that",
    "SB": "Snap back",
    "SB": "Should be",
    "SB": "Smiling back",
    "SBIA": "Standing back in amazement",
    "SBT": "Sorry about that",
    "SC": "Stay cool",
    "SD": "Sweet dreams",
    "SDMB": "Sweet dreams, my baby",
    "SEO": "Search engine optimization",
    "SETE": "Smiling Ear-to-Ear",
    "SFAIK": "So far as I know",
    "SH": "Same here",
    "SH^": "Shut up",
    "SHID": "Slapping head in disgust",
    "SHIP":  "wishing two people were in a relationship",
    "SICNR": "Sorry, I could not resist",
    "SIG2R": "Sorry, I got to run",
    "SIHTH": "Stupidity is hard to take",
    "SIMYC": "Sorry I missed your call",
    "SIR": "Strike it rich",
    "SIS": "sister",
    "SIT": "Stay in touch",
    "SITD": "Still in the dark",
    "SJW": "Social justice warrior",
    "SK8": "Skate",
    "SK8NG": "Skating",
    "SK8R": "Skater",
    "SK8RBOI": "Skater Boy",
    "SLAP": "Sounds like a plan",
    "Slay": "To succeed at something",
    "SM": "Social media",
    "SMAZED": "Smoky haze",
    "SMEXI":  "sexy and Mexican",
    "SMH": "Shaking my head",
    "SMHID": "Scratching my head in disbelief",
    "SNAFU": "Situation normal all fouled up",
    "SNERT": "Snot nosed egotistical rude teenager",
    "SNR": "Streaks and Recents",
    "SO": "Significant other",
    "SOAB": "Son of a bitch",
    "S'OK": " It is okay",
    "SOL": "Sooner or later",
    "SOMY": "Sick of me yet",
    "SorG": "Straight or Gay",
    "SOS": " help",
    "SOS": "Son of Sam",
    "SOT": "Short of time",
    "SOTMG": "Short of time, must go",
    "SOWM": "Someone with me",
    "SPK": "Speak",
    "SRSLY": "Seriously",
    "SPST": "Same place, same time",
    "SPTO": "Spoke to",
    "SQ": "Square",
    "SRY": "Sorry",
    "SS": "So sorry",
    "SSDD": "Same stuff, different day",
    "SSIF": "So stupid it's funny",
    "SSINF": "So stupid it's not funny",
    "ST&D": "Stop texting and drive",
    "STFU": "Shut the fuck up",
    "STR8": "Straight",
    "STW": "Search the Web",
    "SU": "Shut up",
    "SUITM": "See you in the morning",
    "SUL": "See you later",
    "SUP": "What's up",
    "SUTH": "So use to haters",
    "SUX": "sucks",
    "SUYF": "Shut up you fool",
    "SWAK": "Sent with a kiss",
    "SWALK": "Sealed with a loving kiss",
    "SWAT": "Scientific wild *butt* guess",
    "SWL": "Screaming with laughter",
    "SWMBO": "She who must be obeyed",
    "SYL": "See you later",
    "SYS": "See you soon ",
    "SYY": "Shut your yapper",
    "TP": "Think positive",
    "T4BU": "Thanks for being you",
    "T:)T": "Think happy thoughts",
    "TA": "Thanks a lot",
    "TAFN": "That's all for now",
    "TAM": "Tomorrow a.m.",
    "TARFU": "Things Are Really fucked Up.",
    "TAU": "Thinking about you",
    "TAUMUALU": "Thinking about you miss you always love you",
    "TBAG": "disgracing a corpse, taunting a killed player",
    "TBBH": "To be brutally honest",
    "TBC": "To be continued",
    "TBD": "To be determined",
    "TBH": "To be honest",
    "TBL": "Text back later",
    "TBT": "Throwback Thursday",
    "TC": "Take care",
    "TCB": "Take care of business",
    "TCOY": "Take care of yourself",
    "TD": "Tower defense",
    "TD2M": "Talk dirty to me",
    "TDTM": "Talk dirty to me",
    "TEA": "gossip",
    "TFF": "Too fucking funny",
    "TFS": "Thanks for sharing",
    "TFTF": "Thanks for the follow", 
    "TFTI": "Thanks for the invitation",
    "TFTT": "Thanks for this tweet",
    "TG": "Thank goodness",
    "TGIF": "Thank God it's Friday",
    "THNQ": "Thank-you",
    "THNX": "Thanks",
    "THOT": "That wh*re over there",
    "THT": "Think happy thoughts",
    "THX": "Thanks",
    "TIA": "Thanks in advance",
    "TIAD": "Tomorrow is another day",
    "TIC": "Tongue-in-cheek",
    "TIL": "Today I learned",
    "TILIS": "Tell it like it is",
    "TIR": "Teacher in room",
    "TLK2UL8R": "Talk to you later",
    "TL": "Too long",
    "TL;DR": "Too long; didn't read",
    "TM": "Trust me",
    "TMA": "Take my advice",
    "TMB": "Text me back",
    "TMI": "Too much information",
    "TMOT": "Trust me on this",
    "TMTH": "Too much to handle",
    "TMYL": "Tell me your location",
    "TMWFI": "Take my word for it",
    "TNSTAAFL": "There's no such thing as a free lunch",
    "TNT": "Til next time",
    "TOJ": "Tears of joy",
    "TOS": "Terms of service",
    "TOTES": "Totally",
    "TOU": "Thinking of you",
    "TOY": "Thinking of you",
    "TPM": "Tomorrow p.m.",
    "TPTB": "The powers that be",
    "TQ": "Te quiero",
    "TSH": "Tripping so hard",
    "TSNF": "That's so not fair",
    "TSTB": "The sooner, the better",
    "TT": "Trending topic ",
    "TTFN": "Ta ta for now",
    "TTLY": "Totally",
    "TTTT": "These things take time",
    "TTUL": "Talk to you later",
    "TU": "Thank you",
    "TUI": "Turning you in",
    "TURNT": " turned up",
    "TWSS": "That's what she said",
    "TTG": "Time to go",
    "TTYAFN": "Talk to you awhile from now",
    "TTYL": "Talk to you later",
    "TTYS": "Talk to you soon",
    "TY": "Thank you",
    "TYFC": "Thank you for charity",
    "TYFYC": "Thank you for your comment",
    "TYS": "Told you so",
    "TYT": "Take your time",
    "TYSO": "Thank you so much",
    "TYAFY": "Thank you and freak you",
    "TYVM": "Thank you very much",
    "TX": "Thanks",
    "URS": "Up yours",
    "UCMU": "You crack me up",
    "UDI": "Unidentified drinking injury",
    "UDM": "You da man",
    "UDS": "Ugly domestic scene",
    "UFB": "Un freaking believable",
    "UFN": "Until further notice",
    "UFWM": "You freaking with me",
    "UGTBK": "You've got to be kidding",
    "UHGTBSM": "You have got to be fucking kidding me",
    "UKTR": "You know that's right",
    "UL": "Upload",
    "U-L": "You will",
    "UNA": "Use no acronyms",
    "UN4TUN8": "Unfortunate",
    "UNBLEFBLE": "Unbelievable",
    "UNCRTN": "Uncertain",
    "UNPC": "Un politically correct",
    "UOK": "You ok",
    "UR": "You're",
    "UR2YS4ME": "You are too wise for me",
    "URA*": "You are a star",
    "URH": "You are hot",
    "URSKTM": "You are so kind to me",
    "URTM": "You are the man",
    "URW": "You are welcome",
    "USBCA": "Until something better comes along",
    "USU": "Usually",
    "UT": "Unreal Tournament",
    "UT2L": "You take too long",
    "UTM": "You tell me",
    "UV": "Unpleasant visual",
    "UW": "You're welcome",
    "UX": "User experience",
    "V": "Very",
    "VAT": "Value added tax",
    "VBL": "Visible bra line",
    "VBS": "Very big smile",
    "VC": "Voice chat",
    "VFF": "Very freaking funny",
    "VFM": "Value for money",
    "VGC": "Very good condition",
    "VGG": "Very good game",
    "VGH": "Very good hand",
    "VIP": "Very important person",
    "VM": "Voice mail",
    "VN": "Very nice",
    "VNH": "Very nice hand",
    "VoIP": "Voice over Internet Protocol",
    "VRY": "Very",
    "VSC": "Very soft chuckle",
    "VSF": "Very sad face",
    "VWD": "Very well done",
    "VWP": "Very well played",
    "WAN2": "Want to",
    "WAN2TLK": "Want to talk",
    "WAREZ": "pirated software",
    "WAT": "What",
    "WAWA": "Where are we at",
    "WAYF": "Where are you from",
    "W/B": "Write back",
    "WB": "Welcome back",
    "WBS": "Write back soon",
    "WBU": "What about you",
    "WC": "Welcome",
    "WC": "Who cares",
    "WCA": "Who cares anyway",
    "W/E": "Whatever",
    "W/END": "Weekend",
    "WE": "Whatever",
    "WEBO": "Webopedia",
    "WEP": "Weapon",
    "WH5": "Who, what, when, where, why",
    "WHATEVES": "Whatever",
    "WIBNI": "Wouldn't it be nice if",
    "WDALYIC": "Who died and left you in charge",
    "WDYK": "What do you know?",
    "WDYT": "What do you think",
    "WGACA": "What do you think",
    "WIIFM": "What's in it for me",
    "WISP": "Winning is so pleasurable",
    "WITP": "What is the point",
    "WITW": "What in the world",
    "WIU": "Wrap it up",
    "WK": "Week",
    "WKD": "Weekend",
    "WRT": "With regard to",
    "WL": "Whatta loser",
    "W/O": "Without",
    "WOA": "Work of Art",
    "WOMBAT": "Waste of money, brains and time",
    "WOW": "World of Warcraft ",
    "WRK": "Work",
    "WRU": "Where are you?",
    "WRU@": "Where are you at",
    "WRUD": "What are you doing",
    "WTB": "Want to buy",
    "WTF": "What the fuck",
    "WTFE": "What the fuck ever",
    "WTFO": "What the fuck ?, over.",
    "WTG": "Way to go",
    "WTGP": "Want to go private",
    "WTH": "What the heck",
    "WTM": "Who's the man",
    "WTS": "Want to sell",
    "WTT": "Want to trade",
    "WU": "What's up",
    "WUCIWUG": "What you see is what you get",
    "WUF": "Where are you from",
    "WUP": "What's up",
    "WUT": "what",
    "WUW": "What you want",
    "WUU2": "What are you up to",
    "WUZ": "was",
    "WWJD": "What would Jesus do",
    "WWJD": "What Would Judd Do",
    "WWNC": "Will wonders never cease",
    "WWYC": "Write when you can",
    "WYCM": "Will you call me",
    "WYD": "What are you doing",
    "WYGAM": "When you get a minute",
    "WYHAM": "When you have a minute",
    "WYLEI": "When you least expect it",
    "WYSIWYG": "What you see is what you get ",
    "WYWH": "Wish you were here",
    "X": "Kiss",
    "XD": "really hard laugh",
    "XME": "Excuse Me",
    "XOXOXO": "Hugs & Kisses",
    "XLNT": "Excellent ",
    "XLR8": "faster",
    "XPOST": "Cross-post",
    "XYL": "Ex-young lady",
    "XYZ": "Examine your zipper",
    "Y": "Why",
    "Y2K": "You're too kind",
    "YA": "Your",
    "YAA": "Yet another acronym",
    "YABA": "Yet another bloody acronym",
    "YARLY": "Ya, really?",
    "YAS": "praise",
    "YBIC": "Your brother in Christ",
    "YBS": "You'll be sorry",
    "YCDBWYCID": "You can't do business when your computer is down",
    "YCHT": "You can have them",
    "YCLIU": "You can look it up",
    "YCMU": "You crack me up",
    "YCT": "Your comment to?",
    "YD": "Yesterday",
    "YF": "Wife",
    "YG": "Young gentleman",
    "YGG": "You go girl",
    "YGTBKM": "You've got to be kidding me",
    "YGTR": "You got that right",
    "YHBT": "You have been trolled",
    "YHBW": "You have been warned",
    "YHL": "You have lost",
    "YIU": "Yes, I understand",
    "YKW": "You know what",
    "YKWYCD": "You know what you can do",
    "YL": "Young lady",
    "YMMV": "Your mileage may vary",
    "YNK": "You never know",
    "YOLO": "You only live once",
    "YR": "Your",
    "YR": "Yeah right",
    "YRYOCC": "You're running your own cuckoo clock",
    "YSIC": "Your sister in Christ",
    "YSYD": "Yeah sure you do",
    "YT": "YouTube",
    "YTB": "You're the best",
    "YTTL": "You take too long",
    "YTG": "You're the greatest",
    "YW": "You're welcome",
    "YWHNB": "Yes, we have no bananas",
    "YWHOL": "Yelling woohoo out loud",
    "YWSYLS": "You win some, you lose some",
    "YYSSW": "Yeah, yeah, sure, sure, whatever",
    "Z": "Zero",
    "Z%": "Zoo",
    "ZH": "Sleeping Hour",
    "ZOMG": "Oh My God",
    "ZOT": "Zero tolerance",
    "ZUP": "What's up",
    "ZZZZ": "bored"}
    return changed
